### ISSUE TITLE
Bad icon ID error when all icon ID names are valid.

### ISSUE THREAD

**Issue by courtneycb** [BenJetson/octicons-jekyll-include#1]
I have added the following Octicons to my project as follows:

`{% include octicon id="git-branch" size="16" %}`
`{% include octicon id="commit" size="16" %}`
`{% include octicon id="stopwatch" size="16" %}`

Along with copying over the `_octicons` folder and `_include/octicon` file into my project. However when I run the site locally I get the following error for _all_ octicons:

`data:image/svg+xml;base64,bad icon id`

As far as I can see from the [icons list](https://www.bengodfrey.net/octicons-jekyll-include/icons) all of the above IDs are valid?
Super excited to get this working as I would love to use Octicons with GitHub pages! Thanks 😄

**Comment by BenJetson** [comment]
Hi Courtney! Apologies it has taken me so long to respond. This week marks the finish of a very busy semester at university for me (glad that's over 😄).

The `bad icon id` made me suspect that the `octicons` Jekyll collection isn't getting picked up for some reason. After reviewing [my instructions](https://www.bengodfrey.net/octicons-jekyll-include/docs.html#installation) and the [Jekyll documentation](https://jekyllrb.com/docs/collections/) again it appears that I left out this very important step: **you must declare the collection in `_config.yml`**.

Please try adding the following to your `_config.yml`:
```
collections:
  - octicons
```

I will update the instructions accordingly. Thanks so much for bringing this to my attention!

Let me know if this works for you.
